### ISSUE TITLE
Some questions about the input of network

### ISSUE THREAD

**Issue by icech** [jihoonerd/Conditional-Motion-In-Betweening#50]
The input of transformer model is [seq_len, batch_size, embedding_dim] instead of [batch_size, seq_len, embedding_dim], what‘s the purpose of this design？

**Comment by jihoonerd** [comment]
@icech  Torch's default `torch.nn.Transformer` class takes input as `(seq, batch, feature)` order. (refer to [this](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html)). However, if you set `batch_first=True`, then you can use the order you mentioned as well. :)
