### ISSUE TITLE
Benchmark models show different l2p,l2q from the paper

### ISSUE THREAD

**Issue by holyhao** [jihoonerd/Conditional-Motion-In-Betweening#53]
I download the benchmark models from the site, and test it on lanfan dataset. But the l2p and l2q are diffrent from the paper. I wonder if something wrong with my setting. Or, the benchmark models are not the best setting trained models.

**Comment by jihoonerd** [comment]
@holyhao For 40, 60, 80, 120 frame settings, you can reproduce it just with the `test_benchmark.py`. For 30-frame setting, you should manually set `test_window` to 65. I remember that gives the same setting to compare with the benchmark model.

I confirmed the exact same numbers from the paper with the setting above with the weights I uploaded. :)

**Comment by jihoonerd** [comment]
I will leave comment about the `test_window` part.

**Comment by holyhao** [comment]
Thansk for your reply. I follow the test_window as 65  for 30frames test and  it shows the same results as the paper. But, there is some confusion for me . How can test_window infulence the results so much and the test_window only infulence the test data partition.

**Comment by jihoonerd** [comment]
@holyhao I also had same concern that you just mentioned. I agree with your opinion that it should only affect the how the data is prepared, not the end performance. My naive guess is that `test_window` may be related to human motion in terms of periodicity. I remember the effect of window length is reduced in longer horizon settings. However, in the experiment, I just followed the offset and window settings suggested from the original paper and other implementation.
