### ISSUE TITLE
how to conduct the pose-conditioned in-betweening?

### ISSUE THREAD

**Issue by wang-zm18** [jihoonerd/Conditional-Motion-In-Betweening#61]

**Comment by jihoonerd** [comment]
Thank you for your interest in this repo. You can do pose-conditioned in-betweening by inserting valid interim frame(s) on top of starting and target frames in input sequence of the network. You can improve the coverage of the pose-conditioned setting by additionally training the network based on our suggested motion augmentation strategy.

**Comment by wang-zm18** [comment]
Ok, thank you for your reply!
